// Placeholder deck — 40 luxury fashion cards
// Images use picsum.photos for now; swap with real NAP CDN URLs later
const cards = [
  // BAGS
  {
    id: 'b001',
    name: 'The Pouch',
    brand: 'Bottega Veneta',
    category: 'bag',
    image: 'https://picsum.photos/seed/bv-pouch/400/520',
    description: 'Cloud-soft intrecciato leather clutch, utterly unstructured.',
    price: '£1,850',
  },
  {
    id: 'b002',
    name: 'Box Bag',
    brand: 'Céline',
    category: 'bag',
    image: 'https://picsum.photos/seed/celine-box/400/520',
    description: 'Structured leather box with a gold-tone clasp closure.',
    price: '£2,200',
  },
  {
    id: 'b003',
    name: 'Puzzle Bag',
    brand: 'Loewe',
    category: 'bag',
    image: 'https://picsum.photos/seed/loewe-puzzle/400/520',
    description: 'Geometric fold-over leather bag in smooth calfskin.',
    price: '£2,650',
  },
  {
    id: 'b004',
    name: 'Re-Edition 2000',
    brand: 'Prada',
    category: 'bag',
    image: 'https://picsum.photos/seed/prada-re2000/400/520',
    description: 'Mini nylon shoulder bag with gold enamel triangle logo.',
    price: '£970',
  },
  {
    id: 'b005',
    name: 'Le Chiquito',
    brand: 'Jacquemus',
    category: 'bag',
    image: 'https://picsum.photos/seed/jacquemus-chiquito/400/520',
    description: 'Tiny leather bag that started a thousand runway debates.',
    price: '£420',
  },
  {
    id: 'b006',
    name: 'Loulou Puffer',
    brand: 'Saint Laurent',
    category: 'bag',
    image: 'https://picsum.photos/seed/ysl-loulou/400/520',
    description: 'Quilted leather chain bag in a pillow-soft silhouette.',
    price: '£1,695',
  },
  {
    id: 'b007',
    name: 'Baguette',
    brand: 'Fendi',
    category: 'bag',
    image: 'https://picsum.photos/seed/fendi-baguette/400/520',
    description: 'The original It-bag, worn under the arm like a loaf.',
    price: '£2,100',
  },
  {
    id: 'b008',
    name: 'Antigona',
    brand: 'Givenchy',
    category: 'bag',
    image: 'https://picsum.photos/seed/givenchy-antigona/400/520',
    description: 'Sculptural trapezoid tote with polished corner hardware.',
    price: '£1,890',
  },
  {
    id: 'b009',
    name: 'Horsebit 1955',
    brand: 'Gucci',
    category: 'bag',
    image: 'https://picsum.photos/seed/gucci-horsebit/400/520',
    description: 'Leather shoulder bag with a burnished horsebit detail.',
    price: '£1,750',
  },
  {
    id: 'b010',
    name: 'Alexa',
    brand: 'Mulberry',
    category: 'bag',
    image: 'https://picsum.photos/seed/mulberry-alexa/400/520',
    description: 'British icon in heavy grain leather with a postman lock.',
    price: '£895',
  },

  // SHOES
  {
    id: 's001',
    name: 'Hangisi 105',
    brand: 'Manolo Blahnik',
    category: 'shoe',
    image: 'https://picsum.photos/seed/manolo-hangisi/400/520',
    description: 'Jewel-buckle satin pump in midnight blue.',
    price: '£785',
  },
  {
    id: 's002',
    name: 'Pigalle Follies',
    brand: 'Christian Louboutin',
    category: 'shoe',
    image: 'https://picsum.photos/seed/loub-pigalle/400/520',
    description: 'The red-sole stiletto that defined a decade.',
    price: '£695',
  },
  {
    id: 's003',
    name: 'Gianvito 105',
    brand: 'Gianvito Rossi',
    category: 'shoe',
    image: 'https://picsum.photos/seed/gianvito-105/400/520',
    description: 'Suede point-toe pump on a slender stiletto heel.',
    price: '£645',
  },
  {
    id: 's004',
    name: 'Ciao Bella',
    brand: 'Aquazzura',
    category: 'shoe',
    image: 'https://picsum.photos/seed/aquazzura-ciao/400/520',
    description: 'Strappy sandal with a knot detail at the toe.',
    price: '£580',
  },
  {
    id: 's005',
    name: 'Meka Sandal',
    brand: 'Cult Gaia',
    category: 'shoe',
    image: 'https://picsum.photos/seed/cultgaia-meka/400/520',
    description: 'Architectural resin heel sandal, sculptural and minimal.',
    price: '£340',
  },
  {
    id: 's006',
    name: 'Azia 95',
    brand: 'Jimmy Choo',
    category: 'shoe',
    image: 'https://picsum.photos/seed/jimmychoo-azia/400/520',
    description: 'Crystal-embellished mule on a block heel.',
    price: '£750',
  },
  {
    id: 's007',
    name: 'Nudist Song',
    brand: 'Stuart Weitzman',
    category: 'shoe',
    image: 'https://picsum.photos/seed/stuartw-nudist/400/520',
    description: 'Barely-there ankle-strap sandal in nude suede.',
    price: '£440',
  },
  {
    id: 's008',
    name: 'Maureen Mule',
    brand: 'Malone Souliers',
    category: 'shoe',
    image: 'https://picsum.photos/seed/malone-maureen/400/520',
    description: 'Satin mule with a curved grosgrain trim.',
    price: '£395',
  },
  {
    id: 's009',
    name: 'Python Pump',
    brand: 'Paris Texas',
    category: 'shoe',
    image: 'https://picsum.photos/seed/paristexas-python/400/520',
    description: 'Embossed snakeskin pump with a squared toe.',
    price: '£490',
  },
  {
    id: 's010',
    name: 'Air Heart',
    brand: 'Le Specs',
    category: 'shoe',
    image: 'https://picsum.photos/seed/lespecs-heart/400/520',
    description: 'Vintage-inspired flatform slide in tumbled leather.',
    price: '£210',
  },

  // COATS
  {
    id: 'c001',
    name: '101801 Camel Coat',
    brand: 'Max Mara',
    category: 'coat',
    image: 'https://picsum.photos/seed/maxmara-camel/400/520',
    description: 'The definitive camel overcoat in double-faced wool.',
    price: '£2,090',
  },
  {
    id: 'c002',
    name: 'Elgin Coat',
    brand: 'The Row',
    category: 'coat',
    image: 'https://picsum.photos/seed/therow-elgin/400/520',
    description: 'Oversized plaid wool-blend coat with draped lapels.',
    price: '£3,590',
  },
  {
    id: 'c003',
    name: 'Double-Breast Wool Coat',
    brand: 'Toteme',
    category: 'coat',
    image: 'https://picsum.photos/seed/toteme-db/400/520',
    description: 'Clean Scandinavian tailoring in recycled boiled wool.',
    price: '£1,100',
  },
  {
    id: 'c004',
    name: 'Faux-Fur Teddy',
    brand: 'Nanushka',
    category: 'coat',
    image: 'https://picsum.photos/seed/nanushka-teddy/400/520',
    description: 'Shaggy vegan-fur coat in cream, impossibly cosy.',
    price: '£835',
  },
  {
    id: 'c005',
    name: 'Margit Faux-Fur',
    brand: 'Stand Studio',
    category: 'coat',
    image: 'https://picsum.photos/seed/stand-margit/400/520',
    description: 'Belted faux-fur in a warm caramel tone.',
    price: '£680',
  },

  // DRESSES
  {
    id: 'd001',
    name: 'Silk Slip Dress',
    brand: 'Zimmermann',
    category: 'dress',
    image: 'https://picsum.photos/seed/zimm-slip/400/520',
    description: 'Bias-cut silk charmeuse with a lace trim hem.',
    price: '£890',
  },
  {
    id: 'd002',
    name: 'Prairie Dress',
    brand: 'Ulla Johnson',
    category: 'dress',
    image: 'https://picsum.photos/seed/ulla-prairie/400/520',
    description: 'Ruffled floral cotton midi with puffed sleeves.',
    price: '£620',
  },
  {
    id: 'd003',
    name: 'Floral Silk Gown',
    brand: 'Erdem',
    category: 'dress',
    image: 'https://picsum.photos/seed/erdem-floral/400/520',
    description: 'Gathered silk organza with an all-over botanical print.',
    price: '£1,890',
  },
  {
    id: 'd004',
    name: 'Eos Dress',
    brand: 'Cult Gaia',
    category: 'dress',
    image: 'https://picsum.photos/seed/cultgaia-eos/400/520',
    description: 'Slinky halter-neck with a plunging open back.',
    price: '£480',
  },
  {
    id: 'd005',
    name: 'Shoko Dress',
    brand: 'Staud',
    category: 'dress',
    image: 'https://picsum.photos/seed/staud-shoko/400/520',
    description: 'Puffed-sleeve smocked midi in Liberty-print cotton.',
    price: '£295',
  },

  // ACCESSORIES
  {
    id: 'a001',
    name: 'Drop Earrings',
    brand: 'Bottega Veneta',
    category: 'accessory',
    image: 'https://picsum.photos/seed/bv-earrings/400/520',
    description: 'Sterling silver drops with an intrecciato-inspired link.',
    price: '£580',
  },
  {
    id: 'a002',
    name: 'Wool Scarf',
    brand: 'Missoni',
    category: 'accessory',
    image: 'https://picsum.photos/seed/missoni-scarf/400/520',
    description: 'Zigzag knit scarf in a muted autumnal palette.',
    price: '£345',
  },
  {
    id: 'a003',
    name: 'Curb Chain Necklace',
    brand: 'Jennifer Fisher',
    category: 'accessory',
    image: 'https://picsum.photos/seed/jf-chain/400/520',
    description: 'Chunky gold-plated curb chain, the modern statement piece.',
    price: '£390',
  },
  {
    id: 'a004',
    name: 'Deia Hoop Earrings',
    brand: 'Sophie Buhai',
    category: 'accessory',
    image: 'https://picsum.photos/seed/sb-hoops/400/520',
    description: 'Oversized sterling silver hoops with a sculptural twist.',
    price: '£295',
  },
  {
    id: 'a005',
    name: 'Air Heart Sunglasses',
    brand: 'Le Specs',
    category: 'accessory',
    image: 'https://picsum.photos/seed/lespecs-air/400/520',
    description: 'Heart-shaped lenses with a gold wire frame.',
    price: '£69',
  },
  {
    id: 'a006',
    name: 'Monili Belt',
    brand: 'Brunello Cucinelli',
    category: 'accessory',
    image: 'https://picsum.photos/seed/bc-monili/400/520',
    description: 'Hand-strung bead belt in antique gold tones.',
    price: '£1,250',
  },
  {
    id: 'a007',
    name: 'Logo Silk Scarf',
    brand: 'Hermès',
    category: 'accessory',
    image: 'https://picsum.photos/seed/hermes-scarf/400/520',
    description: 'Printed twill silk scarf, 90×90cm, hand-rolled edges.',
    price: '£395',
  },
  {
    id: 'a008',
    name: 'Pearl Ring',
    brand: 'Sophie Buhai',
    category: 'accessory',
    image: 'https://picsum.photos/seed/sb-pearl/400/520',
    description: 'Freshwater baroque pearl set in a sterling silver bezel.',
    price: '£220',
  },
  {
    id: 'a009',
    name: 'Small Silk Bandana',
    brand: 'Toteme',
    category: 'accessory',
    image: 'https://picsum.photos/seed/toteme-bandana/400/520',
    description: 'Monogrammed silk twill in a palette of quiet neutrals.',
    price: '£145',
  },
  {
    id: 'a010',
    name: 'Enamel Bangle',
    brand: 'Valentino',
    category: 'accessory',
    image: 'https://picsum.photos/seed/valentino-bangle/400/520',
    description: 'Bold enamel cuff with a Rockstuds edge.',
    price: '£450',
  },
];

module.exports = { cards };
